[[main]]
  name       = "Home"
  identifier = "home"
  pageRef    = "/"
  weight     = 0

[[main]]
  name       = "Projects"
  identifier = "projects"
  pageRef    = "/projects"
  weight     = 1

[[main]]
  name       = "Blog"
  identifier = "blog"
  pageRef    = "/blog"
  weight     = 2

[[main]]
  name       = "Members"
  identifier = "members"
  pageRef    = "/members"
  weight     = 3

[[main]]
  name       = "Manifesto"
  identifier = "manifesto"
  pageRef    = "/manifesto"
  weight     = 4

[[more]]
  name       = "Contact"
  identifier = "contact"
  pageRef    = "/contact"
  weight     = 1
